import React from 'react';
import Head from 'next/Head';
import NavBar from './NavBar';

export default function Layout({title, children}) {
  return (
    <div className='bg-100'>
      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar >
      {children}
      </NavBar>

    </div>
    
  );
}
