name: Staging deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Add api remote origin
        run: |
          git remote add heroku-api https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/tuture-backend.git
      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix backend heroku-api main
      - name: Add frontend remote origin
        run: |
          git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/tuture-frontend.git
      - name: Deploy frontend to Heroku
        run: |
          git subtree push --prefix frontend-tuture heroku-web main
